### PR TITLE
Panghealth - Doctor appointment app

### PR DESCRIPTION
**Pull request by mullenlucas**
## Implemented features

- Initialized a RoR API app using PostgreSQL as the database manager
- Initialized another repository using React for the Front end:
  - [Link to the Back-end](https://github.com/Ol-create/Doctors_Appointment_Back_End)
  - [Link to the Backend pull request](https://github.com/Ol-create/Doctors_Appointment_Back_End/pull/9)
  - [Link to the Kanban Board of the group](https://github.com/users/Ol-create/projects/2)
- Created the database and performed the necessary relationships
- Added gems for developing the app
- Set up the controllers and models for managing users, doctos, booking, authentication and sessions
- Created rspec evaluations to test their functionality
- Set up the authentication workflow and authorizations for different user permissions
- Configured the app to deploy to onrender

### Important note:
- To work with the PostgreSQL database, we used the `.env` file for setting up the user and password. The repo contains a `.env.example` file which has the format that the `.env` file needs to be. Be sure to change the username and password variable values to the local values.
- The React application also works with an `.env` file for using the backend URL. By default, it is set to look for port 3001 (so the Frontend runs in port 3000 and the backend in 3001). This can be changed by chaning the `.env` file

### CODE REVIEW

**Review by vichuge — COMMENTED** [review]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

mario_ladders


## Suggested changes
_Check the comments under the review._

### Back-end review
- Please, add the secret key to install the back end locally, this could help to improve the review
```
rails aborted!
KeyError: :devise_jwt_secret_key is blank
```
- For this same reason, I couldn't run the tests, please next code reviewer, consider reviewing the tests for this back-end project.

#### Front-end review
- I tried to install the project using `npm install` but I got this error:
```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @material-ui/core@4.12.4
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.10.5
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.9.3" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.10.5
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.9.3" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!   28 more (@emotion/styled, ...)
```
According to the readme file, I could use `npm start` to install, but this doesn't work either. Please consider fixing this. 🐶 

- For this same reason I wasn't able to run the project and see the design or tests,   I kindly invite the next code reviewer to see this. 🐱 

Please feel free to use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mullenlucas** [comment]
Thank you @vichuge for your comments !
We updated the readme files for setting up, as well as the configuration for the master.key on the backend server.
It should now work properly, thanks again for the observations

**Review by vichuge — COMMENTED** [review]
Hi dear student, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

star_wars_almost_there

### Back-end review
- I just forgot to tell you about the last review but, next time try to open a Pull Request for FE and BE too, this helps to review the code and comment lines on both.

- There are some tests could improve, at this point are pending:
```
  1) DoctorsHelper add some examples to (or delete) /Users/vichuge/Documents/microverse/CRs/46/Doctors_Appointment_Back_End/spec/helpers/doctors_helper_spec.rb
     # Not yet implemented
     # ./spec/helpers/doctors_helper_spec.rb:14

  2) UsersHelper add some examples to (or delete) /Users/vichuge/Documents/microverse/CRs/46/Doctors_Appointment_Back_End/spec/helpers/users_helper_spec.rb
     # Not yet implemented
     # ./spec/helpers/users_helper_spec.rb:14

  3) Doctors GET /index add some examples (or delete) /Users/vichuge/Documents/microverse/CRs/46/Doctors_Appointment_Back_End/spec/requests/doctors_spec.rb
     # Not yet implemented
     # ./spec/requests/doctors_spec.rb:5

  4) Users GET /index add some examples (or delete) /Users/vichuge/Documents/microverse/CRs/46/Doctors_Appointment_Back_End/spec/requests/users_spec.rb
     # Not yet implemented
     # ./spec/requests/users_spec.rb:5

Finished in 0.08123 seconds (files took 0.69515 seconds to load)
15 examples, 0 failures, 4 pending
```

### Front-end review
- It looks like the images are not able on the project, please considering fix this for next project:
image

- There aren't tests on FE, please fix this 😄 
image

### Other improvements
Next code reviewer and microverse students: Consider this to improve the instructions for local installation:

- The back end should run on port 3001 (rails s -p 3001)
- The front end run with a local BE deployment
- This is the BE project: https://github.com/Ol-create/Doctors_Appointment_Back_End
(I don't find the URL this second time I review the project)
- When you install the app, delete all .env lines on `config/database.yml` to ignore this and continue. I wasn't able to remember my password/username on my psql installation so, I needed to do this.

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by vichuge — COMMENTED** [review]
Hi dear student, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

star_wars_almost_there

## Suggested changes
_Check the comments under the review._

### Just one more change (do this and the project should be approved for the next reviewer):
- Here, it has a broken link for images too, please fix it. 😄 
image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request merged**
